-- Add new columns to original_records table
ALTER TABLE original_records
    ADD COLUMN IF NOT EXISTS level VARCHAR(50),
    ADD COLUMN IF NOT EXISTS date_join_ongc DATE,
    ADD COLUMN IF NOT EXISTS date_join_post DATE,
    ADD COLUMN IF NOT EXISTS eff_date_prom DATE,
    ADD COLUMN IF NOT EXISTS date_join_area DATE;

-- Update existing columns to match Excel import requirements
ALTER TABLE original_records
    MODIFY COLUMN cpf VARCHAR(20) NOT NULL COMMENT 'CPF NO',
    MODIFY COLUMN name VARCHAR(100) NOT NULL COMMENT 'NAME',
    MODIFY COLUMN designation VARCHAR(100) NOT NULL COMMENT 'DESIGNATION TEXT',
    MODIFY COLUMN level VARCHAR(50) COMMENT 'LEVEL CLASS',
    MODIFY COLUMN section VARCHAR(100) NOT NULL COMMENT 'ORG UNIT TEXT',
    MODIFY COLUMN subsection VARCHAR(100) COMMENT 'POSITION TEXT',
    MODIFY COLUMN dob DATE COMMENT 'DATE OF BIRTH',
    MODIFY COLUMN dor DATE COMMENT 'DATE OF RETIREMENT',
    MODIFY COLUMN mobile VARCHAR(20) NOT NULL COMMENT 'Mobile No',
    MODIFY COLUMN date_join_ongc DATE COMMENT 'DATE OF JOIN ONGC',
    MODIFY COLUMN date_join_post DATE COMMENT 'DATE OF JOIN POST',
    MODIFY COLUMN eff_date_prom DATE COMMENT 'EFF DATE PROM',
    MODIFY COLUMN date_join_area DATE COMMENT 'DATE OF JOIN PER AREA';